// Code generated by go2go; DO NOT EDIT.


//line ./testdata/main.go2:1
package main

//line ./testdata/main.go2:1
import (
//line ./testdata/main.go2:1
 runtime "github.com/ggaaooppeenngg/gogo/runtime"
//line ./testdata/main.go2:1
 "fmt"
//line ./testdata/main.go2:1
 "time"
//line ./testdata/main.go2:1
)

//line ./testdata/main.go2:8
func main() {
//line ./testdata/main.go2:8
  runtime.NewProc(fmt.Println, "vim-go", "123")
				runtime.NewProc(fmt.Println, "vim-go2", "321")
//line ./testdata/main.go2:11
 time.Sleep(time.Second)
	return
}

//line ./testdata/main.go2:13
type Importable୦ int

//line ./testdata/main.go2:13
var _ = runtime.GlobalGoGoRoutines
//line ./testdata/main.go2:13
var _ = fmt.Errorf

//line ./testdata/main.go2:13
const _ = time.ANSIC
